### ISSUE TITLE
Unnecessary nextResolve/nextLoad parameter

### ISSUE THREAD

**Issue by bpstrngr** [nodejs/loaders#126]
Rather just a suggestion, but it would be nice if the loader modules were implemented as a composition instead of callback chains. 
Calling nextResolve in every loader function can be considered biolerplate given shortCircuit:true is the only way to opt out of calling it, otherwise we're ought to throw our own Errors or look forward to get one anyway. The current reason i see for the callback implementation is the limitation of having to pass forward both the url and the context parameter otherwise. But the url could as well be part of the context state, an array including both, or if the loader functions become expected to be GeneratorFunctions, yielding both can support composing multiple return values.

**Comment by GeoffreyBooth** [comment]
We’re quite deep into development to refactor something so fundamental at this point. There was consideration of models like you’re proposing; I can remember all the pros and cons, but a big factor in choosing the “middleware” pattern was so that hooks could modify the responses of later hooks. For example, a `load` hook calls `next` to use `defaultLoad` to get the file contents from disk, and then the hook transpiles it before returning.

**Comment by bpstrngr** [comment]
oh right, this spares a hook to offer to follow each default hook, at least when there is no subsequent step available. i wonder if it's only a separate hook missing for the final transformSource step though, after which no default would be applicable only the runtime to take over, or i'm wrong that the subsequent steps could already serve as post-resolve (and post-load) hooks. thanks for the consideration anyway, appreciate it!
