### ISSUE TITLE
Naming bikeshed - require(esm) interop flag

### ISSUE THREAD

**Issue by guybedford** [nodejs/loaders#221]
As discussed in today's meeting, we need to come up with a name for the flag that will allow require(esm) to support a custom value for a CJS module.

The pattern is that users can write:

```js
export const __cjsModule = true;
export default module.exports;
```

where `module.exports` can be any type of object, which will be returned by `require(esm)` when it sees this `__cjsModule` flag, instead of returning the full namespace.

@joyeecheung suggested a good name might be one that describes what it does, eg `cjsUnwrapDefault`.

It should be unique enough that it will not collide with an existing export name for any ES module in use today.

Opening this thread for further discussion and suggestions, although I'm happy to go with something like @joyeecheung's option here above as well.

**Comment by mcollina** [comment]
I would still prefix it with `__`, so `__cjsUnwrapDefault` would be good for me.

**Comment by guybedford** [comment]
@mcollina thanks, I do tend to support similar, would you be able to share motivation further here for the prefixing?

**Comment by mcollina** [comment]
Let users seeing this it's something internal.

**Comment by guybedford** [comment]
In the case of libraries shipping ES modules that they want to define with
non-object values in CJS, the goal is for authors to add this themselves.
So perhaps that’s an argument against it then?

**Comment by guybedford** [comment]
Okay, agreed that as a user feature and since we have a very unique name, that removing the prefix can be considered. I'm updating the PR to that effect now.

**Comment by ljharb** [comment]
I dunno, it's still a magic string, and `__esModule` is already a thing - `__something` seems like a more consistent and safe choice.

**Comment by marco-ippolito** [comment]
> I dunno, it's still a magic string, and `__esModule` is already a thing - `__something` seems like a more consistent and safe choice.

I agree it should start with `__` so its pretty obvious its an internal

**Comment by joyeecheung** [comment]
__esModule is a convention used by tools and humans are not supposed to hand-write them. But this flag is meant to be hand-written by human beings.

I don’t feel strong enough to insist on it, anyway. Just be aware this flag isn’t private - it will be documented, and is meant to be hand-written by human beings.

**Comment by nicolo-ribaudo** [comment]
If this was not on the module namespace object but on a random object, it would probably be a symbol. It's not to hide it, but just to clearly communicate that it's a special value and not just part of the arbitrary keys namespace that random objects can have.

For example, we have `Symbol.for('nodejs.util.inspect.custom')` and we don't just ready a random `utilInspectCustom` property on objects, even if that symbol is for hand-written custom inspection implementations that libraries can provide for their objects.

We cannot have symbols on module namespaces, but we should still have some visual marker that says "this property is somewhat different from the other exports".

**Comment by joyeecheung** [comment]
I wonder if we can do this instead:

```js
function foo() {}

export { foo as "module.exports" };  // Or prefix it with `nodejs`
export default foo;
```

**Comment by ljharb** [comment]
That's already a valid export name, though (as are all strings), so I don't think it avoids the need for a human-visible string indicator that it's internal to node, like `__`.

**Comment by joyeecheung** [comment]
These are all valid names, but `"module.exports"` is probably special and Node.js specific enough (that and string names tend to be rarer than normal names already).

**Comment by joyeecheung** [comment]
> We could either error, or allow it. Erroring would catch more mistakes, but allowing it would make it possible to write code like

I think it's always better to give more options to the users, and let linters catch these mistakes instead of closing the doors with a runtime error.

**Comment by guybedford** [comment]
I like the sentiment of `module.exports` here, but one of the goals of this work is to align this interop with the wrappers produced when requiring a CJS module from ESM (via `import('cjs')`), so that they will also reflect this marker. In that case having the standard representation of CJS in ESM have this shape of `Namespace { 'module.exports', default, ...detectedNames }`might introduce more confusion for consumers of CJS modules who aren't even aware of this interop history in future in terms of which import to use, and especially when combined with the fact that users would use this feature for tricks where the default export and `module.exports` values may or may not then match it may result in some unintended consequences.

We've already incurred the cost of the conceptual simplicity of the `default` export exactly representing CJS `module.exports` for ESM wrappers, as it was designed for in TC39. This interop problem for defaults and named exports cases was already the difficult tradeoff we had to make and is part of the Node.js compat model now. If we hadn't yet made this decision I'd be more sympathetic here to models where `module.exports` captures the CJS value and default could be flexible (and Joyee it would have been so great if you'd been around for those discussions, this would have been an interesting path!). But unfortunately, we just can't entertain those kinds of models at this point due to compat.

Given we have the `default` export model for CJS representation in ESM, the private marker remains my preference. And the `__` prefix was also my original choice. The original consensus in this bikeshed discussion was to remove it, but since others chimed in the consensus shifted to include it. Therefore I've added back this prefix in the PR at https://github.com/nodejs/node/pull/54563.

**Comment by joyeecheung** [comment]
I propose that we do a poll either within TSC or among the bigger collaborator/user base. WDYT?

**Comment by joyeecheung** [comment]
>  In that case having the standard representation of CJS in ESM have this shape of Namespace `{ 'module.exports', default, ...detectedNames }` might introduce more confusion for consumers of CJS modules who aren't even aware of this interop history in future in terms of which import to use

This assumes that we actually want to mutate the CJS wrapper namespace, which I don't think we have consensus about anyway. If `{ 'module.exports', default, ...detectedNames }`  can look confusing to those who `import(cjs)` in the future, I am not sure why `{ __ cjsUnwrapDefault, default, ...detectedNames }` can look less confusing. I would just suggest for the purpose of detecting imported CJS, we go with the alternative suggested in https://github.com/nodejs/node/pull/53848#issuecomment-2244500584

```js
import { isCJSModule } from 'node:module';  // Or use process.getBuiltinModule();
import * as empty from './empty.cjs';
isCJSModule(empty);  // true

// Instead of checking empty.whateverFlag that is added by Node.js to CJS wrappers
```

I think that would be a less confusing and more generally useful API overall. So we get two more intuitive APIs, instead of introducing a cryptic API that tries to do both.

**Comment by ljharb** [comment]
Would there be a similar predicate for isESMModule?

Either way wouldn’t those predicates cause changing format to be a breaking change? (which it is now, but hopefully require(esm) allows it to no longer be one)

**Comment by guybedford** [comment]
> This assumes that we actually want to mutate the CJS wrapper namespace, which I don't think we have consensus about anyway

There are two confusions I was pointing out, and I'll repeat the arguments so these are clear:

1. As an ESM importer importing CJS, what if I start _relying_ on the `module.exports` instead of `default` export name? This is a choice for users to make, and perhaps some patterns will emerge for one over the other. The confusion specifically being, which to use.
2. As an ESM importer importing ESM that was designed to be consumed by CJS, I will also get this `module.exports` property, which in that case _may or may not_ also come with a `default` export. The confusion here being that `module.exports` and `default` diverge, but as the consumer I don't necessarily know if I'm importing CJS or ESM so this introduces semantic ambiguity to me as the consumer of the module as to the expectation when importing a module.

Using the `default` aligns the **consumer expectation** on a default import in both cases, removing ambiguity. And where interop is a complex enough space, removing ambiguity helps build alignment between libraries and tools.

@joyeecheung this is a naming bikeshed discussion, not a debate over `isCJSModule`. I've engaged fully on these issues. I think it would be best if you make your intent explicit - either request a block on https://github.com/nodejs/node/pull/53848 landing or not and we can then continue process from there.

**Comment by joyeecheung** [comment]
I find those questions are a bit far-fetched. How often do people import * from a package and decide to what export to use based on personal guessing about the name, without consulting the documentation? I feel that in most cases, you just follow (copy-paste) what the documentation tells you to use. If there are any undocumented exports, a regular user is not even likely to notice them, or would not think about using them unless they know what they are doing.

**Comment by nicolo-ribaudo** [comment]
> If there are any undocumented exports, a regular user is not even likely to notice them

This is unfortunately not true, as editor autocompletion shows all the available exports.

**Comment by joyeecheung** [comment]
Using the import syntax, how do you actually get the string name autocompleted though? At least when I try with VSCode, it doesn't work with string names. It's also another story about how the import ... from ... syntax itself doesn't work with autocomplete that well in the first place - personally I have rarely used it with import syntax because of this, and when I do I already know what export I am looking for (otherwise I don't know what to type after import). When I am using a library I don't know well, I just copy paste the import statement from the documentation.

We could also just suggest editors not to autocomplete that specific name anyway (if they do support it). Is this concern really worth asking the package authors to hand-write a more cryptic export?

**Comment by nicolo-ribaudo** [comment]
> Using the import syntax, how do you actually get the string name autocompleted though? At least when I try with VSCode, it doesn't work with string names.

You need to use TypeScript 5.6 beta, which is the only TS version that supports `export { x as "y" }` and it's not released in VSCode yet. Given this file:
```js
let a;
export { a };
export { a as "x" };
export { a as "module.exports" };
```

I get these suggestions:
![image](https://github.com/user-attachments/assets/3bb949ae-f064-47d4-8d71-710c74f9add4)

**Comment by ert78gb** [comment]
I am following this thread for a while and hesitated to share my thoughts.

Honestly, I am really curious about the future of the `commonjs`. If it will part of the node.js ecosystem forever then make sense to improve it and align with es6 module. But if `commonjs` will remove in the next 2 LTS version I think make no sense to put any effort on it.

I don't think node.js need to support 2 module system in long term. As far as I know `commonjs` is not part of the EcmaScript standard so it could be removed because it will not break the web.

Remove `commonjs` will a pain on short term but I don't think it will bigger pain than maintaining 2 module system. Longterm the Node.js core team and library maintainers will win from the retirement of the `commonjs`

Sorry if I hurt someone with this thought, but sometimes have to sacrifice things for a bigger one.

**Comment by aduh95** [comment]
My not so informed preference would be:

1. Always unwrap default export if it's the only export (although I've been told that might be too "magical", but IMO it's always going to feel magical no matter what we decide, and I think that's actually the most straight forward thing from a user perspective).
2. `export { myDefaultExport as "module.exports" }` – the rule of thumb being "if you re-defined `module.exports` in CJS, you must export it as such when refactoring to ESM"
3. `export const __cjsUnwrapDefault = true`
4. `export const cjsUnwrapDefault = true`

**Comment by joyeecheung** [comment]
> Always unwrap default export if it's the only export 

This would make adding named exports to the ESM semver-major, though. Also previously a CommonJS package can do something like this to provide both default and named exports to their CJS + ESM users:

```js
class Klass { static foo() {} };
module.exports = Klass;
module.exports.foo = Klass.foo;  // make the lexer detect this
```

If only the single default exports can be unwrapped for CJS users,  they need to choose between either breaking CJS users for keeping named exports, or breaking ESM users for losing the named exports. That would demotivate migration to ESM in the first place. But if we want to add a marker to help with the case where both default and named exports, then it would be less of a footgun to require it always when there is a default export/it used to reassign `module.exports`.

**Comment by ert78gb** [comment]
> Personally I am not a believer of paternalistic breaking changes - we should set the breaking timeline based on how much the usage of CommonJS has dropped in the ecosystem instead of a paternalistic"X versions later".

Sometimes, have to kindly push people to the right direction. 

The https://github.com/wooorm/npm-esm-vs-cjs/ is really nice chart, but if I want to show the esm has bigger part of the bar then I can find the way of it.
Just an example the top 25 package from the https://github.com/wooorm/npm-esm-vs-cjs/blob/main/data/2024-08-28.json 
- esm => 12 (48%)
- dual => 6 (24%)
- faux => 0 (0%)
- cjs => 7 (28%)

If I say dual modules already made the esm transitions then I can say 72% vs 28% the winner is esm.
This is why I believe only in statistics that I made (faked). :)
The last 25 packages are all cjs. 

Honestly, I don't know what is the good measurement. Maybe worth to check the trend of the new packages too.

There is nothing to force the commonjs transition to esm because commonjs works with both environment. But people started it because it has benefit. It is the official js module that supported by browser, better treeshaking, etc.
The maintainers of commonjs packages or applications start the feel the pain when they would like to use a pure esm package and based on top of the top high-impact npm packages the chance higher day by day. If you deliver the require(esm) feature then you eliminate problem so the commonjs will with us forever.

I don't wanna force anyone to do anything but please consider how will affect the require(esm) feature to the whole node.js ecosystem. I as a developer who use node.js 60 hours/week feel the pain of some earlier made decision that was full with good will, but it was not fully finished or bought up new requirement/problems that has not been solved in the last 2.5 years.

n.b. The `import` function is and was the workaround in the last 5 years in the commonjs packages. Not the best solution but it worked and helped in the transition for me.

**Comment by ljharb** [comment]
Nobody needs a push for anything. If the incentive - the pull - isn't sufficient, then the new thing simply isn't better.

**Comment by jsumners-nr** [comment]
This is not the thread to discuss the which module systems to keep or drop from Node.js.

**Comment by joyeecheung** [comment]
Marked the off-topic comments as off-topic. @ert78gb if you want to propose breaking CommonJS, please open a separate issue.

**Comment by guybedford** [comment]
The vote concluded today in favour of `module.exports` in https://github.com/nodejs/TSC/pull/1622 per https://github.com/nodejs/loaders/issues/221#issuecomment-2325062946. Will update the relevant PRs in this direction.

**Comment by magic-akari** [comment]
I understand this thread aims to resolve interoperability challenges when importing ESM packages from CJS environments. Currently, CJS imports receive the entire ESM namespace as an object, making it impossible to achieve the CJS-style behavior of importing only specific exported functions through this interoperability layer.

Since introducing `module.exports` successfully solves this at runtime, how should compilers (like Babel, SWC, etc.) interpret this pattern? 

### For transpilation scenarios converting ESM to CJS, if a compiler detects the `module.exports` export pattern in ESM code, should it directly apply the following transformation?

**Input (ESM):**
```javascript
function foo() {}

export { foo as "module.exports" };
export default foo;
```

**Output (CJS):**
```javascript
function foo() {}

module.exports = foo;
// Other exports would be overwritten or discarded
```

**Comment by magic-akari** [comment]
I realize it might be late to contribute to this discussion, but if possible, I'd like to note that TypeScript's `export =` syntax achieves precisely this functionality. Standardizing this in ESM could potentially offer a more robust solution:

1. When `export =` is present in ESM, it should prohibit all other exports
2. ESM consumers should only be able to use default imports
3. CJS consumers should import directly without needing the `namespace.default` pattern

**Comment by joyeecheung** [comment]
If someone is willing to draft a proposal, champion it in TC39, get it implemented by enough engines to reach stage 4, we can consider adopting it when V8 implements it and provide an API for the embedder to tell the syntax is used. Though that might take years or never get through the committee. In the mean time, using the existing export syntax with a chosen name is the best we can do for CJS modules with default exports to go ESM-only without breaking backwards compatibility. (This is not new syntax, just a chosen export name not too different from `exports['__esModule']`, so no changes in V8 parser is needed).

**Comment by joyeecheung** [comment]
> For transpilation scenarios converting ESM to CJS, if a compiler detects the module.exports export pattern in ESM code, should it directly apply the following transformation?

The most intuitive handling is probably what's described, and tools can either choose to error/warn when the default export is not the same as the string export, or do nothing, or make it configurable. Even if nothing is done on the tool's side, emitting code as-is with the existing CJS default export handling (with __esModule) should already work as long as modules make sure the two exports match, so it's mostly an optimisation/UX feature that tools can decide to implement or not.

**Comment by magic-akari** [comment]
> Even if nothing is done on the tool's side, emitting code as-is with the existing CJS default export handling (with __esModule) should already work as long as modules make sure the two exports match, so it's mostly an optimisation/UX feature that tools can decide to implement or not.

Since the current transformation might output code like this:
```javascript
exports.__esModule = true;
exports["module.exports"] = expr;
```

If this works without modification, **does that imply** Node.js also supports this specific identifier (`"module.exports"`) within CommonJS modules?

**Comment by joyeecheung** [comment]
The situation is:

1. Real CommonJS consumers can get unwrapped default exports from real ESM based on the "module.exports" adaptor
2. Faux ESM consumers can get unwrapped default exports from real ESM based on __esModule adapter tools add into their code in older Node.js, and the "module.exports" adaptor Node.js consumes in newer versions
3. Real CommonJS consumers (that don't have the __esModule adapter in their code) still need to unwrap .default from faux ESM as before - changing it is a breakage that we can no longer afford anymore
4. Faux ESM consumers still rely on the __esModule adapter tools add in their code to unwrap .default from faux ESM

**Comment by joyeecheung** [comment]
Actually to maintain 3, it's better for tools to not change anything from what they are already doing. The idea is that for module authors, module.exports should match default, and should not be used alone without an accompanying default export. So this would be what gets generated for faux-ESM providers that use the string export when they do it correctly and also use default exports:

```js

exports.__esModule = true;
exports.default = expr;
exports["module.exports"] = expr;
```

For faux ESM consumers, there's practically no difference if the adaptors emitted by tools don't change. For real CommonJS consumers there's also no difference - they still need to unwrap default manually as before. Node.js doesn't do anything for require(cjs) or require(faux-esm) because that would break existing unwrapping code.
